language: scala
sudo: false

scala:
  - 2.11.12
  - 2.12.6

jdk:
  - oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10
  - nvm use 10
  - export NODE_PATH="$(npm config get prefix)"/lib/node_modules
  - npm install
  - npm install jsdom@11 source-map-support

script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

